version: "0.1"
user: mayurp
key: y1BYjotgPNHSRbRXuh1wndsTPgYFvSWokaWQxINfrErF6P7ijE
testSuites: []
pre: [nuget locals all -clear, dotnet build HyperTestDemos.sln -c Debug]
runson: win
autosplit: true
concurrency: 10
testDiscovery:
  command: dotnet run --project HyperTestDiscoverer/HyperTestDiscoverer.csproj /Users/lambdatest/Documents/HyperTestDemos/HyperTestDemo/bin/Debug/netcoreapp3.1/HyperTestDemo.dll
  mode: static
  type: raw
testDiscoveryResult:
- HyperTestDemo.CheckoutPage10Tests.SuccessfullyPruchaseItem0
- HyperTestDemo.CheckoutPage10Tests.SuccessfullyPruchaseItem1
- HyperTestDemo.CheckoutPage10Tests.SuccessfullyPruchaseItem2
- HyperTestDemo.CheckoutPage10Tests.SuccessfullyPruchaseItem3
- HyperTestDemo.CheckoutPage10Tests.SuccessfullyPruchaseItem4
- HyperTestDemo.CheckoutPage10Tests.SuccessfullyPruchaseItem5
- HyperTestDemo.CheckoutPage10Tests.SuccessfullyPruchaseItem6
- HyperTestDemo.CheckoutPage10Tests.SuccessfullyPruchaseItem7
- HyperTestDemo.CheckoutPage10Tests.SuccessfullyPruchaseItem8
- HyperTestDemo.CheckoutPage10Tests.SuccessfullyPruchaseItem9
- HyperTestDemo.CheckoutPage1Tests.SuccessfullyPruchaseItem0
- HyperTestDemo.CheckoutPage1Tests.SuccessfullyPruchaseItem1
- HyperTestDemo.CheckoutPage1Tests.SuccessfullyPruchaseItem2
- HyperTestDemo.CheckoutPage1Tests.SuccessfullyPruchaseItem3
- HyperTestDemo.CheckoutPage1Tests.SuccessfullyPruchaseItem4
- HyperTestDemo.CheckoutPage1Tests.SuccessfullyPruchaseItem5
- HyperTestDemo.CheckoutPage1Tests.SuccessfullyPruchaseItem6
- HyperTestDemo.CheckoutPage1Tests.SuccessfullyPruchaseItem7
- HyperTestDemo.CheckoutPage1Tests.SuccessfullyPruchaseItem8
- HyperTestDemo.CheckoutPage1Tests.SuccessfullyPruchaseItem9
- HyperTestDemo.CheckoutPage2Tests.SuccessfullyPruchaseItem0
- HyperTestDemo.CheckoutPage2Tests.SuccessfullyPruchaseItem1
- HyperTestDemo.CheckoutPage2Tests.SuccessfullyPruchaseItem2
- HyperTestDemo.CheckoutPage2Tests.SuccessfullyPruchaseItem3
- HyperTestDemo.CheckoutPage2Tests.SuccessfullyPruchaseItem4
- HyperTestDemo.CheckoutPage2Tests.SuccessfullyPruchaseItem5
- HyperTestDemo.CheckoutPage2Tests.SuccessfullyPruchaseItem6
- HyperTestDemo.CheckoutPage2Tests.SuccessfullyPruchaseItem7
- HyperTestDemo.CheckoutPage2Tests.SuccessfullyPruchaseItem8
- HyperTestDemo.CheckoutPage2Tests.SuccessfullyPruchaseItem9
- HyperTestDemo.CheckoutPage3Tests.SuccessfullyPruchaseItem0
- HyperTestDemo.CheckoutPage3Tests.SuccessfullyPruchaseItem1
- HyperTestDemo.CheckoutPage3Tests.SuccessfullyPruchaseItem2
- HyperTestDemo.CheckoutPage3Tests.SuccessfullyPruchaseItem3
- HyperTestDemo.CheckoutPage3Tests.SuccessfullyPruchaseItem4
- HyperTestDemo.CheckoutPage3Tests.SuccessfullyPruchaseItem5
- HyperTestDemo.CheckoutPage3Tests.SuccessfullyPruchaseItem6
- HyperTestDemo.CheckoutPage3Tests.SuccessfullyPruchaseItem7
- HyperTestDemo.CheckoutPage3Tests.SuccessfullyPruchaseItem8
- HyperTestDemo.CheckoutPage3Tests.SuccessfullyPruchaseItem9
- HyperTestDemo.CheckoutPage4Tests.SuccessfullyPruchaseItem0
- HyperTestDemo.CheckoutPage4Tests.SuccessfullyPruchaseItem1
- HyperTestDemo.CheckoutPage4Tests.SuccessfullyPruchaseItem2
- HyperTestDemo.CheckoutPage4Tests.SuccessfullyPruchaseItem3
- HyperTestDemo.CheckoutPage4Tests.SuccessfullyPruchaseItem4
- HyperTestDemo.CheckoutPage4Tests.SuccessfullyPruchaseItem5
- HyperTestDemo.CheckoutPage4Tests.SuccessfullyPruchaseItem6
- HyperTestDemo.CheckoutPage4Tests.SuccessfullyPruchaseItem7
- HyperTestDemo.CheckoutPage4Tests.SuccessfullyPruchaseItem8
- HyperTestDemo.CheckoutPage4Tests.SuccessfullyPruchaseItem9
- HyperTestDemo.CheckoutPage5Tests.SuccessfullyPruchaseItem0
- HyperTestDemo.CheckoutPage5Tests.SuccessfullyPruchaseItem1
- HyperTestDemo.CheckoutPage5Tests.SuccessfullyPruchaseItem2
- HyperTestDemo.CheckoutPage5Tests.SuccessfullyPruchaseItem3
- HyperTestDemo.CheckoutPage5Tests.SuccessfullyPruchaseItem4
- HyperTestDemo.CheckoutPage5Tests.SuccessfullyPruchaseItem5
- HyperTestDemo.CheckoutPage5Tests.SuccessfullyPruchaseItem6
- HyperTestDemo.CheckoutPage5Tests.SuccessfullyPruchaseItem7
- HyperTestDemo.CheckoutPage5Tests.SuccessfullyPruchaseItem8
- HyperTestDemo.CheckoutPage5Tests.SuccessfullyPruchaseItem9
- HyperTestDemo.CheckoutPage6Tests.SuccessfullyPruchaseItem0
- HyperTestDemo.CheckoutPage6Tests.SuccessfullyPruchaseItem1
- HyperTestDemo.CheckoutPage6Tests.SuccessfullyPruchaseItem2
- HyperTestDemo.CheckoutPage6Tests.SuccessfullyPruchaseItem3
- HyperTestDemo.CheckoutPage6Tests.SuccessfullyPruchaseItem4
- HyperTestDemo.CheckoutPage6Tests.SuccessfullyPruchaseItem5
- HyperTestDemo.CheckoutPage6Tests.SuccessfullyPruchaseItem6
- HyperTestDemo.CheckoutPage6Tests.SuccessfullyPruchaseItem7
- HyperTestDemo.CheckoutPage6Tests.SuccessfullyPruchaseItem8
- HyperTestDemo.CheckoutPage6Tests.SuccessfullyPruchaseItem9
- HyperTestDemo.CheckoutPage7Tests.SuccessfullyPruchaseItem0
- HyperTestDemo.CheckoutPage7Tests.SuccessfullyPruchaseItem1
- HyperTestDemo.CheckoutPage7Tests.SuccessfullyPruchaseItem2
- HyperTestDemo.CheckoutPage7Tests.SuccessfullyPruchaseItem3
- HyperTestDemo.CheckoutPage7Tests.SuccessfullyPruchaseItem4
- HyperTestDemo.CheckoutPage7Tests.SuccessfullyPruchaseItem5
- HyperTestDemo.CheckoutPage7Tests.SuccessfullyPruchaseItem6
- HyperTestDemo.CheckoutPage7Tests.SuccessfullyPruchaseItem7
- HyperTestDemo.CheckoutPage7Tests.SuccessfullyPruchaseItem8
- HyperTestDemo.CheckoutPage7Tests.SuccessfullyPruchaseItem9
- HyperTestDemo.CheckoutPage8Tests.SuccessfullyPruchaseItem0
- HyperTestDemo.CheckoutPage8Tests.SuccessfullyPruchaseItem1
- HyperTestDemo.CheckoutPage8Tests.SuccessfullyPruchaseItem2
- HyperTestDemo.CheckoutPage8Tests.SuccessfullyPruchaseItem3
- HyperTestDemo.CheckoutPage8Tests.SuccessfullyPruchaseItem4
- HyperTestDemo.CheckoutPage8Tests.SuccessfullyPruchaseItem5
- HyperTestDemo.CheckoutPage8Tests.SuccessfullyPruchaseItem6
- HyperTestDemo.CheckoutPage8Tests.SuccessfullyPruchaseItem7
- HyperTestDemo.CheckoutPage8Tests.SuccessfullyPruchaseItem8
- HyperTestDemo.CheckoutPage8Tests.SuccessfullyPruchaseItem9
- HyperTestDemo.CheckoutPage9Tests.SuccessfullyPruchaseItem0
- HyperTestDemo.CheckoutPage9Tests.SuccessfullyPruchaseItem1
- HyperTestDemo.CheckoutPage9Tests.SuccessfullyPruchaseItem2
- HyperTestDemo.CheckoutPage9Tests.SuccessfullyPruchaseItem3
- HyperTestDemo.CheckoutPage9Tests.SuccessfullyPruchaseItem4
- HyperTestDemo.CheckoutPage9Tests.SuccessfullyPruchaseItem5
- HyperTestDemo.CheckoutPage9Tests.SuccessfullyPruchaseItem6
- HyperTestDemo.CheckoutPage9Tests.SuccessfullyPruchaseItem7
- HyperTestDemo.CheckoutPage9Tests.SuccessfullyPruchaseItem8
- HyperTestDemo.CheckoutPage9Tests.SuccessfullyPruchaseItem9
- HyperTestDemo.DemoTests.SuccessfullyPruchaseItem0
testRunnerCommand: dotnet test HyperTestDemos.sln --filter FullyQualifiedName=$test
globalTimeout: 150
testSuiteTimeout: 150
testSuiteStep: 150
retryOnFailure: true
maxRetries: 5
jobID: e274ae8a-210b-493f-b4c4-1353bb07f11a
mergeArtifacts: true
codeDirectory: HyperTestDemos
